<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AuthNinja.DemoApi</RootNamespace>
    <AssemblyName>AuthNinja.DemoApi</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\adapters\dotnet\src\AuthNinja.AspNetCore\AuthNinja.AspNetCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests/**" />
    <Content Remove="tests/**" />
    <None Remove="tests/**" />
  </ItemGroup>

</Project>
