import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { FullStack } from "./detect-stack.js";

const DEFAULT_DATABASE_URL = "postgresql://postgres:postgres@localhost:5432/auth_ninja";

function serverEnvTemplate(stack: FullStack, secret: string): string {
  const baseUrl = stack === "next" ? "http://localhost:3000" : "http://localhost:5280";

  return `# Auth-Ninja configuration (never commit .env)

AUTH_NINJA_SECRET=${secret}
AUTH_NINJA_BASE_URL=${baseUrl}
AUTH_NINJA_DATABASE_URL=${DEFAULT_DATABASE_URL}

# Sessions
AUTH_NINJA_SESSION_IDLE_MINUTES=15
AUTH_NINJA_SESSION_ABSOLUTE_HOURS=8

# Lockout
AUTH_NINJA_LOCKOUT_MAX_ATTEMPTS=5
AUTH_NINJA_LOCKOUT_WINDOW_MINUTES=15
AUTH_NINJA_LOCKOUT_DURATION_MINUTES=30

# 2FA
AUTH_NINJA_REQUIRE_2FA=false
AUTH_NINJA_2FA_ISSUER=AuthNinja

# Passkeys
AUTH_NINJA_PASSKEYS_ENABLED=true
AUTH_NINJA_PASSKEY_RP_ID=localhost

# IP audit
AUTH_NINJA_IP_AUDIT_ENABLED=true

# API guard
AUTH_NINJA_API_RATE_LIMIT=100
AUTH_NINJA_CSRF_ENABLED=true

# Optional Redis (recommended for multi-instance production)
# AUTH_NINJA_REDIS_URL=redis://localhost:6379
`;
}

const EXAMPLE_TEMPLATE = `# Auth-Ninja configuration (copy to .env — never commit .env)

AUTH_NINJA_SECRET=                          # generated by: pnpm dlx @auth-ninja/cli setup
AUTH_NINJA_BASE_URL=http://localhost:3000
AUTH_NINJA_DATABASE_URL=postgresql://postgres:postgres@localhost:5432/auth_ninja

# Sessions
AUTH_NINJA_SESSION_IDLE_MINUTES=15
AUTH_NINJA_SESSION_ABSOLUTE_HOURS=8

# Lockout
AUTH_NINJA_LOCKOUT_MAX_ATTEMPTS=5
AUTH_NINJA_LOCKOUT_WINDOW_MINUTES=15
AUTH_NINJA_LOCKOUT_DURATION_MINUTES=30

# 2FA
AUTH_NINJA_REQUIRE_2FA=false
AUTH_NINJA_2FA_ISSUER=AuthNinja

# Passkeys
AUTH_NINJA_PASSKEYS_ENABLED=true
AUTH_NINJA_PASSKEY_RP_ID=localhost

# IP audit
AUTH_NINJA_IP_AUDIT_ENABLED=true

# API guard
AUTH_NINJA_API_RATE_LIMIT=100
AUTH_NINJA_CSRF_ENABLED=true

# Optional Redis (recommended for multi-instance production)
# AUTH_NINJA_REDIS_URL=redis://localhost:6379
`;

export const DOTNET_VITE_ENV_LINES = `
# React SPA (Vite) — public client vars, no secrets
VITE_AUTH_BASE_URL=http://localhost:5173
AUTH_NINJA_PROXY_TARGET=http://localhost:5280
`;

export type ScaffoldEnvOptions = {
  cwd?: string;
  stack?: FullStack;
  secret?: string;
};

export type ScaffoldEnvResult = {
  envCreated: boolean;
  envExampleCreated: boolean;
  secretInjected: boolean;
  viteLinesAppended: boolean;
};

async function writeIfMissing(path: string, content: string): Promise<boolean> {
  if (existsSync(path)) {
    return false;
  }

  await writeFile(path, content, "utf8");
  return true;
}

async function injectSecret(path: string, secret: string): Promise<boolean> {
  const current = await readFile(path, "utf8");
  if (/^AUTH_NINJA_SECRET=.{32,}/m.test(current)) {
    return false;
  }

  if (/^AUTH_NINJA_SECRET=/m.test(current)) {
    const updated = current.replace(/^AUTH_NINJA_SECRET=.*$/m, `AUTH_NINJA_SECRET=${secret}`);
    await writeFile(path, updated, "utf8");
    return true;
  }

  await writeFile(path, `AUTH_NINJA_SECRET=${secret}\n${current}`, "utf8");
  return true;
}

/** Create `.env` / `.env.example` when missing; inject secret when absent. */
export async function scaffoldEnv(options: ScaffoldEnvOptions = {}): Promise<ScaffoldEnvResult> {
  const cwd = options.cwd ?? process.cwd();
  const stack = options.stack ?? "next";
  const secret = options.secret ?? "";
  const envPath = join(cwd, ".env");
  const envExamplePath = join(cwd, ".env.example");

  const envCreated = secret
    ? await writeIfMissing(envPath, serverEnvTemplate(stack, secret))
    : await writeIfMissing(envPath, EXAMPLE_TEMPLATE);

  let secretInjected = false;
  if (!envCreated && secret && existsSync(envPath)) {
    secretInjected = await injectSecret(envPath, secret);
  }

  const envExampleCreated = await writeIfMissing(envExamplePath, EXAMPLE_TEMPLATE);

  let viteLinesAppended = false;
  if (stack === "dotnet" && existsSync(envPath)) {
    const current = await readFile(envPath, "utf8");
    if (!current.includes("VITE_AUTH_BASE_URL")) {
      await writeFile(envPath, `${current.trimEnd()}\n${DOTNET_VITE_ENV_LINES}`, "utf8");
      viteLinesAppended = true;
    }
  }

  return { envCreated, envExampleCreated, secretInjected, viteLinesAppended };
}

/** @deprecated Use scaffoldEnv — kept for tests importing the template constant shape. */
export const AUTH_NINJA_ENV_TEMPLATE = EXAMPLE_TEMPLATE;
